AllCops:
  Exclude:
    - "spec/dummy/**/*"
  SuggestExtensions: false

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: True
Lint/StructNewOverride:
  Enabled: True

Style/ExponentialNotation:
  Enabled: True
Style/HashEachMethods:
  Enabled: True
Style/HashTransformKeys:
  Enabled: True
Style/HashTransformValues:
  Enabled: True

RSpec/FilePath:
  Enabled: False

Gemspec/OrderedDependencies:
  Enabled: False

Bundler/OrderedGems:
  Enabled: False
