# https://docs.rubocop.org/rubocop/

AllCops:
  NewCops: enable
  SuggestExtensions: true

plugins:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-rspec_rails
  - rubocop-performance

Style/StringLiterals:
  EnforcedStyle: double_quotes
